services:
  react-app:
    container_name: react_craco_prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${PROD_PORT}:80'
    env_file:
      - .env
