version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production   
    container_name: love_note_prod
    ports:
      - "80:3000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    container_name: mysql_love_note
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: always

volumes:
  db_data:
