version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: love_note_prod_dev
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    entrypoint: sh -c "./scripts/entrypoint.sh"
    restart: 'unless-stopped'
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql_love_note
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: 'unless-stopped'

volumes:
  db_data:
