services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_dev
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: sh -c "npx wait-on tcp:db:${DB_PORT} && npm run dev"
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql_container
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
