services:
  app:
    build: .
    container_name: node_app
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - app_data:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  app_data:
  db_data:
