version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: love_note_prod
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    container_name: mysql_love_note
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'lovenote'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always

volumes:
  db_data:
