version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "lovenote"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lovenet

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - lovenet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    env_file:
      - ../frontend/.env
    volumes:
      - ../frontend/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - lovenet

volumes:
  db_data:

networks:
  lovenet:
# docker compose -p lovenote-sern up -d
# docker compose -p lovenote-sern down -v
# docker restart lovenote-sern-backend-1
# docker exec -it lovenote-sern-backend-1 npm run fresh:db
